### ISSUE TITLE
BUG: mops publish no longer works

### ISSUE THREAD

**Issue by crusso** [ZenVoich/setup-mops#1]
https://github.com/ZenVoich/setup-mops/blob/53b42fe40975b17b5e7f55112dc08f2f33746f51/action.yml#L90

Should that now by `mops user import`?

**Comment by crusso** [comment]
c.f. https://github.com/dfinity/motoko-base/actions/runs/10901092595/job/30250151766

**Comment by ZenVoich** [comment]
Yes, thank you for report

**Comment by ZenVoich** [comment]
Fixed

**Comment by crusso** [comment]
Thank you very much for the quick fix!

**Comment by crusso** [comment]
I tried re-running the action but have one more problem
We used to pass `--no-encrypt` but that's no longer recognized?

https://github.com/dfinity/motoko-base/actions/runs/10901092595/job/30308958528

Any suggestions?

**Comment by crusso** [comment]
Oh hang on, its your own action that specifies `--no-encrypt`. Maybe that needs changing here too. @ZenVoich

**Comment by ZenVoich** [comment]
Seems I overlooked a bug with the `mops user *` commands. Will fix soon...

**Comment by ZenVoich** [comment]
Fixed in mops cli 1.0.1

**Comment by crusso** [comment]
Excellent, that seems to have worked!

https://mops.one/base
